metadata:
  name: android-x86
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 2G
      # This will request an Intel GPU for the Android-x86 pod.
      # It requires the Intel GPU device plugin, see
      # https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin/README.md
      limits:
        gpu.intel.com/i915: 1
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          bus: virtio
  volumes:
    - name: registryvolume
      registryDisk:
        image: quay.io/quamotion/android-x86:7.1-r2
