metadata:
  name: android-x86
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"image": "quay.io/quamotion/android-x86-hook:7.1-r2"}]'
    smbios.vm.kubevirt.io/baseBoardManufacturer: Radical Edward
    video.vm.kubevirt.io/vgpu: "a297db4a-f4c2-11e6-90f6-d3b88d6c9525"
    graphics.vm.kubevirt.io/eglHeadless: "true"
  name: android-x86
spec:
  domain:
    resources:
      requests:
        memory: 2G
      # This will request an Intel vGPU for the Android-x86 pod.
      # It requires the Intel GPU device plugin, see
      # https://github.com/kubedroid/intel-device-plugins-for-kubernetes/tree/vgpu
      limits:
        gpu.intel.com/i915-v: 1
        gpu.intel.com/i915: 1
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          bus: virtio
  volumes:
    - name: registryvolume
      registryDisk:
        image: quay.io/quamotion/android-x86-disk:7.1-r2
