metadata:
  name: android-x86
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"image": "quay.io/quamotion/android-x86-hook:7.1-r2"}]'
    smbios.vm.kubevirt.io/baseBoardManufacturer: Radical Edward
    video.vm.kubevirt.io/model: virtio
    # This requires a newer version of libvirt
    graphics.vm.kubevirt.io/eglHeadless: enabled
  name: android-x86
spec:
  domain:
    resources:
      requests:
        memory: 2G
      # This will request an Intel GPU for the Android-x86 pod.
      # It requires the Intel GPU device plugin, see
      # https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin/README.md
      limits:
        gpu.intel.com/i915: 1
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          bus: virtio
  volumes:
    - name: registryvolume
      registryDisk:
        image: quay.io/quamotion/android-x86:8.1-rc2
