apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubedroid.fullname" . }}-android-x86-injector
  labels:
    app.kubernetes.io/name: {{ include "kubedroid.name" . }}-android-x86-injector
    helm.sh/chart: {{ include "kubedroid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubedroid.name" . }}-android-x86-injector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubedroid.name" . }}-android-x86-injector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}/android-x86-injector:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
secretName: android-x86-injector