apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kubedroid.fullname" . }}-intel-vgpu-plugin
  labels:
    app.kubernetes.io/name: {{ include "kubedroid.name" . }}-intel-vgpu-plugin
    helm.sh/chart: {{ include "kubedroid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubedroid.name" . }}-intel-vgpu-plugin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubedroid.name" . }}-intel-vgpu-plugin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: intel-vgpu-plugin
          image: "{{ .Values.image.repository }}/intel-vgpu-plugin:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: sysfs
            mountPath: /sys
          - name: kubeletsockets
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins