
[[override]]
   name = "kubevirt.io/containerized-data-importer"
   source = "https://github.com/kubevirt/containerized-data-importer"
   version="=v1.3.0"

[[override]]
  name = "kubevirt.io/kubevirt"
  source = "https://github.com/kubevirt/kubevirt"

[[override]]
  name = "k8s.io/client-go"
  version="kubernetes-1.11.4"

[[override]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.11.4"

[[override]]
  name="github.com/go-kit/kit"
  revision="fe6fe28ba0d54b39f27e79cddba4911b7e4fffc7"
